### ISSUE TITLE
Homebrew install does not work on macOS High Sierra

### ISSUE THREAD

**Issue by ferdisn** [theseal/ssh-askpass#24]
Hi, I am a KeePassXC user and I installed ssh-askpass via Homebrew but it didn't work. Tried installing it manually (use vi and copy the texts from this repo) and is working now.

The installer in Homebrew asked me to `sudo brew services start theseal/ssh-askpass/ssh-askpass` and after restart, when I ran `ssh add -l` it complained about `Error connecting to ssh-agent`. Revert the command, and reran without sudo, it ran, it displayed through `launchctl list`, but when I tried to add the key (via KeePassXC) it didn't accept anything.

So I proceeded by removing the homebrew version, and install it manually. It's working flawlessly now.

**Comment by theseal** [comment]
Did you use `sudo` when installing `ssh-askpass` with `brew`? I can't otherwise understand why `brew` would request you to use `sudo` when enabling the service. `sudo` isn't needed to either run or install `ssh-askpass`. 

I never heard of this feature in KeePassXC but I must say that it looks cool! Just tried it out by installing the application and adding my private key to an empty database. It all worked just fine but seems to require a reboot. Don't think `ssh-agent -l` is suppose to give any output when you use KeePassXC as agent since it's not the regular `ssh-agent` you are using. On my computer with KeePassXC as agent I get the following result:
```
$ ssh-agent -l
launch_activate_socket(): No such process
```
But ssh is clearly using an agent an forcing me to accept the use of the key.

Did you when you installed and reverted the installation reboot the machine in between and after? All this `launchctl` magic has unfortunately been more and more like black magic (and race-conditaionish) in later macOS.

**Comment by simmel** [comment]
@ferdisn did you have a chance to try this? #22 should have solved not telling us to use `sudo`.

Can you try it and confirm that KeepassXC works? Would also be helpful for #23

**Comment by ferdisn** [comment]
HI, I haven't tried it, yet. I'll get back to you in a week (It's a mac Mini).
