### ISSUE TITLE
Sometimes "System Events" gets stuck and blocks ssh-askpass

### ISSUE THREAD

**Issue by MichaelRoosz** [theseal/ssh-askpass#48]
We encounter two issues when using ssh-askpass for a while:
- sometimes ssh-askpass does not open any dialog - when this happens we see a "System Events" running in the background which we have to kill to fix the issue
- sometimes the ssh process tries to close/kill ssh-askpass - this fails because the "System Events" process still stays open. this causes the ssh authentication to fail.

Both issues are fixed for us, when we remove the reference to "System Events":
https://github.com/MichaelRoosz/ssh-askpass/commit/cd0285854ee7034c4abe7120bd9500c1c408ba70

**Comment by simmel** [comment]
Which OS X version are you running?

If System Events is behaving badly I suspect the installation has other problems as well since it's a core functionality in OS X see https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/AutomatetheUserInterface.html

**Comment by MichaelRoosz** [comment]
macOS 13.5.1, everything is running fine, it is happening on at least 20 other macBooks, I doubt they are all broken.

also, since we removed the call to "System Events" ssh-askpass is running perfectly.

**Comment by simmel** [comment]
Thank you for your contribution @MichaelRoosz !

Sorry for the long wait, AFK-life got busy. I've fixed up your commit and pushed it.
